### PR TITLE
Line division for results file

### PR DESCRIPTION
**Pull request by rupole1185**
Manuele,

this is the fix to the line division in "Note" field of the result file. I just have a doubt on the FDS file comparison [which I am going to test later today]. I wanted to give you something anyway!

### CODE REVIEW

**Comment by rupole1185** [comment]
Emanuele, I was a bit doubtfull because of the high number of differences in lines in some files produced. I confirm it is correct (I made a couple of manual checks and I got the same results).

For me we can merge the braches

**Comment by emanuelegissi** [comment]
Great, thanks for the update.

**Comment by rupole1185** [comment]
@emanuelegissi this pull request now contains the solution for the issue #13 [the file is imported correctly]

**Comment by rupole1185** [comment]
Manuele, this pull request regards the validation import from the FDS official repository (issue https://github.com/firetools/blenderfds28x/issues/23)

**Comment by emanuelegissi** [comment]
Sorry for the delay, I had to complete the work on qgis2fds.
There is a lot here. Not dealing exclusively with line division. I prefer split pull requests.

**Pull request closed without merging**
